### ISSUE TITLE
技术周刊投稿 - 谈谈浏览器中富文本编辑器的技术演进

### ISSUE THREAD

**Issue by Sheetaa** [SearchFeed/weekly#139]
- 标题：谈谈浏览器中富文本编辑器的技术演进
- 链接：https://mp.weixin.qq.com/s/8TSxm2q0kQrVA9AaUE0I7g
- 类别：拓展阅读 JavaScript
- 来源： 微信公众号 - 抖音前端技术团队
- 推荐理由（文章评论/解读）：富文本编辑器的技术演进分为三个阶段：L0完全依赖于浏览器 API 的阶段；L1部分依赖浏览器 API 进行编辑渲染的阶段；L2基本脱离浏览器能力自己实现的阶段
- 您的名字：希达

**Comment by robbenmu** [comment]
这篇完全扯蛋的。ueditor本身就是vm搞得，Slate是基于Quill搞得，ueditor和Quill没区别
