### ISSUE TITLE
技术周刊投稿 - 2021 年 JavaScript 明星项目公布，最受欢迎的竟是它？

### ISSUE THREAD

**Issue by okaychen** [SearchFeed/weekly#183]
- 标题：2021 年 JavaScript 明星项目公布，最受欢迎的竟是它？
- 链接：https://mp.weixin.qq.com/s/vG0nNRT4MJv6Qq5X5-vg-A
- 类别：JavaScript 扩展阅读 2021回顾
- 来源：weixin
- 推荐理由（文章评论/解读）：为构建更好的网站和应用程序，元框架时代已悄然来临。Next.js、Nuxt、SvelteKit以及Remix等框架都为开发者了更多的可能
- 您的名字：okaychen

**Comment by Sheetaa** [comment]
和这篇重复了 2021 JavaScript Rising Stars

**Comment by okaychen** [comment]
> 和这篇重复了 2021 JavaScript Rising Stars

嗯嗯 好，我发前面那个
