### ISSUE TITLE
技术周刊投稿 - CONTENT-AWARE IMAGE RESIZING IN JAVASCRIPT

### ISSUE THREAD

**Issue by Sheetaa** [SearchFeed/weekly#4]
- 标题：CONTENT-AWARE IMAGE RESIZING IN JAVASCRIPT
- 链接：https://trekhleb.dev/blog/2021/content-aware-image-resizing-in-javascript/
- 类别：算法、图像处理
- 来源：trekhleb.dev
- 推荐理由（文章评论/解读）：如果缩放图片时宽高缩放比例不一致，会导致图像内容发生形变“失真”。使用 Seam Carving 算法可以解决这个问题，它会尽可能保持图像中“重要区域”的比例，避免由于直接缩放造成的“失真”。在实现上还需要借助动态规划算法去寻找最优 Seam。文章作者还提供了一个 Demo 工具 JS IMAGE CARVER 供大家提交自己的图片测试效果。
- 您的名字：希达

**Comment by ksky521** [comment]
标题：从零开始写一个微前端框架
链接：https://github.com/micro-zoe/micro-app/issues/17
类别：微前端
来源：github
推荐理由（文章评论/解读）：这篇文章从零开始搭建一个微前端框架，从技术选型开始，逐步为读者展现了一个微前端框架。全篇文章分为渲染、沙盒、样式隔离、数据通信四篇。
您的名字：三水清
